// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgRdnfIzOP7yN9a9BWJtayPALsZ_voLg',
    appId: '1:623428847751:web:4268faa2db2367d25a1022',
    messagingSenderId: '623428847751',
    projectId: 'tapmate-fyp',
    authDomain: 'tapmate-fyp.firebaseapp.com',
    storageBucket: 'tapmate-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcjXZJBtrGDUzuAo5V2xQVPt6P7P40wxA',
    appId: '1:623428847751:android:152fc9f72087b79d5a1022',
    messagingSenderId: '623428847751',
    projectId: 'tapmate-fyp',
    storageBucket: 'tapmate-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-ntUUaAZJGwE3uyn3D6rIU2rqGpzEaI',
    appId: '1:623428847751:ios:42128e7c35d4a8985a1022',
    messagingSenderId: '623428847751',
    projectId: 'tapmate-fyp',
    storageBucket: 'tapmate-fyp.firebasestorage.app',
    iosBundleId: 'com.example.tapmatefyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-ntUUaAZJGwE3uyn3D6rIU2rqGpzEaI',
    appId: '1:623428847751:ios:42128e7c35d4a8985a1022',
    messagingSenderId: '623428847751',
    projectId: 'tapmate-fyp',
    storageBucket: 'tapmate-fyp.firebasestorage.app',
    iosBundleId: 'com.example.tapmatefyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVgRdnfIzOP7yN9a9BWJtayPALsZ_voLg',
    appId: '1:623428847751:web:992ab64e4a39e9fd5a1022',
    messagingSenderId: '623428847751',
    projectId: 'tapmate-fyp',
    authDomain: 'tapmate-fyp.firebaseapp.com',
    storageBucket: 'tapmate-fyp.firebasestorage.app',
  );
}
